In [19]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.documents import Document

In [10]:
from dotenv import load_dotenv

load_dotenv()

True

In [11]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [12]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,9789027712059 Since the three volume edition o...

In [13]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [14]:
with open("tagged_description.txt", "w", encoding="utf-8") as f:
    for description in books["tagged_description"]:
        f.write(str(description) + "\n")

In [15]:
from langchain_community.document_loaders import TextLoader

raw_documents = TextLoader('tagged_description.txt', encoding="utf-8").load()
# Split by newline to get individual descriptions
documents = []
for line in raw_documents[0].page_content.split('\n'):
    if line.strip():  # Skip empty lines
        documents.append(Document(page_content=line))

In [16]:
documents[0]

Document(metadata={}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [20]:
from langchain_community.embeddings import HuggingFaceEmbeddings

# Use a free, open-source model
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db_books = Chroma.from_documents(
    documents,
    embedding=embeddings
)

C:\Users\nasty\AppData\Local\Temp\ipykernel_26848\3026897354.py:4: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

D:\Mitacs GRI 2026 PROOFS\Book Recommender\llm-semantic-book-recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\nasty\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [21]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='4a3f4c81-e476-447a-ac83-0e95ab218b03', metadata={}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='a80aa5ee-91a3-4e48-8b5c-ed38abef9fd9', metadata={}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='a80f297d-6d75-4551-880f-007312af0429', metadata={}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='b4a8b49c-5cc9-434c-bb19-29594b599405', metadata={}, page_content="9780060959036 Barbara Kingsolver's fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel's intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."),
 Document(id='15772b33-8534-4b3b-a9b1-2304a9530281', metadata={}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='5cd8c331-f377-42a0-9141-5a886391bbdc', metadata={}, page_content="9780374522599 The Control of Nature is John McPhee's bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."),
 Document(id='94684fbb-63ac-40f0-b563-b9610b9882e4', metadata={}, page_content='9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub.'),
 Document(id='08bb4584-2ed1-4113-a68b-62c729950851', metadata={}, page_content="9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author's father].' 'BL. 1986 Children's Editors' Choices (BL) Children's Choices for 1987 (IRA/CBC) Notable 1986 Childrens' Trade Books in Social Studies (NCSS/CBC) 1986 Children's Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"),
 Document(id='afa476f7-b050-4a84-95a8-48816a15de4b', metadata={}, page_content="9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat's community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it's hard to evade questions forever. Children's Choices for 1991 (IRA/CBC)VOYA's Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"),
 Document(id='28894c14-dcf5-41b3-9319-7b4139809eb8', metadata={}, page_content="9780802431486 Drawn from years of counseling and the author's own parenting experiences, this valuable resource, filled with Scripture passages and accompanying practical applications, provides principles for raising and nurturing children in these uncertain and rapidly changing times. Original.")]

In [22]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,9780786808069 Children will discover the excit...

In [23]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [24]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,9780007151240 It should be the most natural th...
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,9780060959036 Barbara Kingsolver's fifth novel...
334,9780060976118,006097611X,Operation Wandering Soul,Richard Powers,Fiction,http://books.google.com/books/content?id=nIGIm...,"Highly imaginative and emotionally powerful, t...",1994.0,3.62,352.0,366.0,9780060976118 Highly imaginative and emotional...
383,9780061144899,0061144894,When the Heart Waits,Sue Monk Kidd,Religion,http://books.google.com/books/content?id=JlP91...,From the Bestselling Author of The Secret Life...,2006.0,4.17,240.0,2141.0,9780061144899 From the Bestselling Author of T...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,"9780064402453 ‘Racso, a brash and boastful lit..."
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,9780064403870 When Margaret and her younger br...
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,"9780064404419 ""Culled from 69 stories collecte..."
416,9780064406925,006440692X,Winter on the Farm,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=IvlKH...,The Little House books tell the story of a lit...,1997.0,4.13,32.0,400.0,9780064406925 The Little House books tell the ...
427,9780064434874,0064434877,Christmas in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=FT1Yp...,"Long ago, a little girl named Laura Ingalls li...",1997.0,4.19,32.0,2062.0,"9780064434874 Long ago, a little girl named La..."
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,9780064434980 Even the youngest child can enjo...
436,9780064471961,0064471969,Shade's Children (rack),Garth Nix,Juvenile Fiction,http://books.google.com/books/content?id=_jlgl...,The Key to Survival Rests in the Hands of Shad...,1998.0,3.90,345.0,10368.0,9780064471961 The Key to Survival Rests in the...
568,9780140139976,0140139974,Sailor Song,Ken Kesey,Fiction,http://books.google.com/books/content?id=-pPSO...,"In Alaska to film a famous children's book, th...",1993.0,3.57,533.0,1956.0,9780140139976 In Alaska to film a famous child...
991,9780192862099,019286209X,The Origins of Life,John Maynard Smith;Eörs Szathmáry,Science,http://books.google.com/books/content?id=nHDbB...,'I can recommend this book as a thoroughly int...,2000.0,4.11,192.0,41.0,9780192862099 'I can recommend this book as a ...
1078,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,340101.0,9780241003008 Eric Carle's children's classic ...
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,9780374422080 This Newbery Honor Book tells th...
1642,9780374522599,0374522596,The Control of Nature,John McPhee,Nature,http://books.google.com/books/content?id=p1qKQ...,The Control of Nature is John McPhee's bestsel...,1990.0,4.24,288.0,3365.0,9780374522599 The Control of Nature is John Mc...
1907,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in...,William Cronon,Law,http://books.google.com/books/content?id=w04mj...,"Essays by revisionist historians, scientists, ...",1996.0,4.16,560.0,649.0,9780393315110 Essays by revisionist historians...
1943,9780393959055,0393959058,"Walden ; And, Resistance to Civil Government",Henry David Thoreau,Literary Collections,http://books.google.com/books/content?id=uVxnQ...,The classic chronicle of a communion with natu...,1992.0,3.95,482.0,232.0,9780393959055 The classic chronicle of a commu...
2126,9780439569729,0439569729,SCHOLASTIC SUCCESS WITH 4TH GRADE(WORKBOOK),Terry Cooper,Education,http://books.google.com/books/content?id=b-EBH...,"416 bright, colorful pages that give kids prac...",2003.0,4.57,416.0,7.0,"9780439569729 416 bright, colorful pages that ..."
2164,9780439994798,0439994799,His Dark Materials,Philip Pullman,"Children's stories, English",http://books.google.com/books/content?id=E9ZkG...,The trilogy follows the coming of age of two c...,2001.0,4.26,1296.0,304.0,9780439994798 The trilogy follows the coming o...
2216,9780440421702,0440421705,Hoot,Carl Hiaasen,Bullying,http://books.google.com/books/content?id=uKUTo...,"Roy, who is new to his small Florida community...",2006.0,3.82,292.0,83557.0,"9780440421702 Roy, who is new to his small Flo..."
2261,9780446518628,044651862X,The Celestine Prophecy,James Redfield,Fiction,http://books.google.com/books/content?id=UXolx...,You have never read a book like this before --...,1994.0,3.63,247.0,1280.0,9780446518628 You have never read a book like ...
2409,9780451456816,0451456815,Not of Woman Born,Constance Ash;Robert A. Silverberg,Fiction,http://books.google.com/books/content?id=nOEIA...,A collection of stories that detail modern sci...,1999.0,3.80,288.0,59.0,9780451456816 A collection of stories that det...
2457,9780465016907,0465016901,The Drama of the Gifted Child,NaN,Psychology,http://books.google.com/books/content?id=TgtTz...,Why are many of the most successful people pla...,1997.0,4.09,144.0,11373.0,9780465016907 Why are many of the most success...
2497,9780486256429,0486256421,Galapagos,William Beebe,Nature,http://books.google.com/books/content?id=wFKrG...,More than 100 splendid illustrations enhance t...,1988.0,3.84,528.0,31.0,9780486256429 More than 100 splendid illustrat...
2718,9780553382617,0553382616,The Shelters of Stone,Jean M. Auel,Fiction,http://books.google.com/books/content?id=BmAgt...,In the fifth volume of the best-selling Earth'...,2004.0,3.82,891.0,33918.0,9780553382617 In the fifth volume of the best-...
2776,9780553585803,0553585800,Forty Signs of Rain,Kim Stanley Robinson,Fiction,http://books.google.com/books/content?id=TI18I...,In the first installment of a trilogy of eco-t...,2005.0,3.54,393.0,2956.0,9780553585803 In the first installment of a tr...
2827,9780571207565,0571207561,Collected Children's Stories,Sylvia Plath,"Children's poetry, American",http://books.google.com/books/content?id=i6oCG...,"Three classic children's stories, Mrs Cherry's...",2001.0,4.22,54.0,111.0,9780571207565 Three classic children's stories...
2897,9780618111206,0618111204,Once a Wolf,Stephen R. Swinburne;Jim Brandenburg,Juvenile Nonfiction,http://books.google.com/books/content?id=UkZWu...,With powerful and rare photos by a former phot...,2001.0,4.06,48.0,42.0,9780618111206 With powerful and rare photos by...
3000,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJ...,"With more than half a million copies in print,...",1986.0,4.15,395.0,2083.0,9780671631987 With more than half a million co...
3214,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,28261.0,9780689861130 Children will love joining in an...
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,9780744578263 Washed up on the beach during a ...
3577,9780762413935,076241393X,The Classic Treasury of Hans Christian Andersen,Hans Christian Andersen;Christian Birmingham,Juvenile Fiction,http://books.google.com/books/content?id=cYout...,Award-winning English illustrator Christian Bi...,2002.0,4.24,156.0,107.0,9780762413935 Award-winning English illustrato...
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,9780763620875 When Judy Moody gets serious abo...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,"9780786808397 Introduce your baby to birds, ca..."
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,9780786812912 In her first illustrated book fo...
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,9780786819119 Charming illustrations and playf...
3834,9780802431486,0802431488,The 10 Commandments of Parenting,H. Edwin Young,Religion,http://books.google.com/books/content?id=Q1Hxj...,Drawn from years of counseling and the author'...,2005.0,4.00,224.0,25.0,9780802431486 Drawn from years of counseling a...
3933,9780811205467,0811205460,Turtle Island,Gary Snyder,Poetry,http://books.google.com/books/content?id=xilff...,These Pulitzer Prize-winning poems and essays ...,1974.0,4.09,112.0,3717.0,9780811205467 These Pulitzer Prize-winning poe...
4103,9780842331913,0842331913,Four Mothers at Chautauqua,Isabella Alden,Fiction,http://books.google.com/books/content?id=DkbhZ...,"Isabella Alden, Grace Livingston Hill's aunt a...",1997.0,4.01,265.0,27.0,"9780842331913 Isabella Alden, Grace Livingston..."
4185,9780878937202,087893720X,Essentials of Conservation Biology,Richard B. Primack,Science,http://books.google.com/books/content?id=spaGQ...,Essentials of Conservation Biology (Fourth Edi...,2006.0,3.89,585.0,36.0,9780878937202 Essentials of Conservation Biolo...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...
4331,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,218.0,9781400033850 Describes the influence of a fou...
4607,9781561796779,1561796778,"Boomers, Xers, and Other Strangers",Rick Hicks;Kathy Hicks,Social Science,http://books.google.com/books/content?id=IogMA...,The authors maintain that children's core valu...,1999.0,3.36,384.0,28.0,9781561796779 The authors maintain that childr...
4713,9781576839546,1576839540,Parenting with Love and Logic,Foster Cline;Jim Fay,Family & Relationships,http://books.google.com/books/content?id=TpCtP...,Cline and Fay offer advice to help parents rai...,2006.0,4.07,271.0,9486.0,9781576839546 Cline and Fay offer advice to he...
4898,9781593851170,1593851170,The Nature of Play,Anthony D. Pellegrini;Peter K. Smith,Psychology,http://books.google.com/books/content?id=Nukz6...,"""Comprehensive and up to date, this tightly ed...",2005.0,4.25,308.0,4.0,"9781593851170 ""Comprehensive and up to date, t..."
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,9788122200850 This book is the story of a youn...